status = error
name = RiskEngineLogConfig

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %c{1} - %m%n

rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

logger.riskengine.name = frauddetection.risk
logger.riskengine.level = info

logger.spark.name = org.apache.spark
logger.spark.level = info

logger.streaming.name = org.apache.spark.sql.execution.streaming
logger.streaming.level = info

logger.kafka.name = org.apache.kafka
logger.kafka.level = info
